### ISSUE TITLE
problem with loading a filter

### ISSUE THREAD

**Issue by mjvakili** [cmancone/ezgal#2]
Hi. When I run the example, 

plot( zs, model.get_rest_ml_ratios( zf, filters='sloan_i', zs=zs ), 'k-', label='Sloan i' )

I run into this error: 
**ValueError: Pass a numpy array with the vega spectrum to calculate vega conversion!**

Similarly, I get the same error when I try to add a new filter.

**Comment by themiyan** [comment]
@mjvakili did you manage to get this issue sorted?

**Comment by mjvakili** [comment]
@themiyan yes I managed to get it to work  
 by doing something similar to this:
`model = ezgal.model("bc03_burst_0.1_z_0.02_chab.model")
model.add_filter("i.dat" , "omega_cam" , units = "nm")
`
where "bc03_burst_0.1_z_0.02_chab.model" is downloaded from the ezgal website

**Comment by smorawetz** [comment]
@mjvakili Hi, I'm experiencing the same issue as you mentioned earlier. I tried copying your code from your recent comment, and am still getting the same error. Could you share more of your code so I have more context?

Thanks

**Comment by boada** [comment]
@stewm0 It's because the vega reference spectrum is not being installed with the rest of the package. I bet the other people here are just running things from the source directory, and you are installing things with `python setup.py install`. 

Check out https://docs.python.org/3.6/distutils/setupscript.html#installing-package-data

You can also look at my recent fork for a fix.

**Comment by mjvakili** [comment]
@stewm0 sorry I totally forgot to respond! 
The code is the same. As @boada pointed out, it's most likely the package itself that's not installed properly on your machine. You might want to install it directly from the source.

**Comment by smorawetz** [comment]
@boada You're exactly right, as I eventually figured out. Thanks for the response

If installed with pip, as recommended on the EzGal website, one has to install the data file (found here) separately, as it contains some standardized information (e.g. vega spectrum).

**Comment by mjvakili** [comment]
Closing this issue

**Comment by RuancunLi** [comment]
@stewm0 Hi, I am also dealing with this problem. Where can I find the the ``data" file? I mean, that the model information is easy to download, which stored on the EzGal website. However, I couldn't find the filters information, especially the standardized vega spectrum.

**Comment by boada** [comment]
It's included in the package. 

easyGalaxy/ezgal/data/refs/vega.fits
